### ISSUE TITLE
Add support for multiple meta-languages

### ISSUE THREAD

**Issue by stefanocoretta** [lexa-tools/lexaR#4]
For example

```
senses:
  se_01:
    id: se_01
    gloss:
      en: "cat"
      fr: "chat"
    definition:
      en: "a cat [Felis Catus]"
      fr: "un chat [Felis Catus]"
```
